"""
Generate the model-derived equation files included by the Supplementary
Information.

The script builds the zero-policy model and each individual 2% policy model,
but does not compile or solve them.  Every mathematical expression is rendered
from the registered JCGE equation AST through `JCGEOutput`; no equation is
written manually in this script.  Repeated indexed instances are grouped into
equation families so that the Supplementary Information reports the complete
model specification without printing thousands of calibration-specific copies.
"""

using CERiseCGE
using JCGECore
using JCGEOutput
using JCGERuntime

const PROJECT_ROOT = normpath(joinpath(@__DIR__, "..", ".."))
const GENERATED_DIR = joinpath(PROJECT_ROOT, "article", "generated")
const CORE_OUTPUT = joinpath(GENERATED_DIR, "si_model_equation_inventory.tex")
const POLICY_OUTPUT = joinpath(GENERATED_DIR, "si_policy_equation_inventory.tex")

const POLICY_LISTING_SCENARIOS = (
    (:virgin_metal_tax, 0.02, "Virgin-metal tax"),
    (:recycling_support, -0.02, "Recycling support"),
    (:refurbishment_support, -0.02, "Refurbishment support"),
    (:repair_support, -0.02, "Repair support"),
    (:reuse_support, -0.02, "Reuse support"),
)

function _build_context(model::CERiseCGE.MultiRegionModelSpec)
    spec = CERiseCGE.run_spec(model)
    ctx = JCGERuntime.KernelContext()
    for block in spec.model.blocks
        JCGECore.build!(block, ctx, spec)
    end
    return ctx
end

function _canonical_block(block::Symbol)
    text = String(block)
    match_result = match(
        r"^(production|eol_productivity_production|material_composite_production)_[A-Z]+$",
        text,
    )
    return match_result === nothing ? block : Symbol(only(match_result.captures))
end

function _equation_expression(equation)
    payload = equation.payload
    payload isa NamedTuple || return nothing
    expression = get(payload, :expr, nothing)
    return expression isa JCGECore.EquationExpr ? expression : nothing
end

function _family_key(equation)
    return (_canonical_block(equation.block), equation.tag)
end

function _equation_families(ctx::JCGERuntime.KernelContext)
    grouped = Dict{Tuple{Symbol,Symbol},Vector{NamedTuple}}()
    for equation in JCGERuntime.list_equations(ctx)
        equation.block === :calibrated_initial_values && continue
        _equation_expression(equation) === nothing && continue
        push!(get!(grouped, _family_key(equation), NamedTuple[]), equation)
    end
    return grouped
end

function _latex_escape(value)
    text = string(value)
    return replace(text,
        "\\" => "\\textbackslash{}",
        "_" => "\\_",
        "&" => "\\&",
        "%" => "\\%",
        "#" => "\\#",
        "{" => "\\{",
        "}" => "\\}",
    )
end

function _family_expression_signatures(families)
    signatures = Dict{Tuple{Symbol,Symbol},Set{String}}()
    for (key, equations) in families
        signatures[key] = Set(
            JCGEOutput.render_expr(_equation_expression(equation); format=:latex)
            for equation in equations
        )
    end
    return signatures
end

function _write_family(io::IO, key, equations;
    instance_label::AbstractString="registered")
    block, tag = key
    representative = first(equations)
    expression = _equation_expression(representative)
    expression === nothing && error("Equation family $(key) has no mathematical expression.")
    count_text = length(equations) == 1 ? "1 $(instance_label) instance" :
        "$(length(equations)) $(instance_label) instances"
    println(io, "\\paragraph{\\texttt{$(_latex_escape(block)).$(_latex_escape(tag))}} ($count_text).")
    println(io, "\\[")
    println(io, JCGEOutput.render_expr(expression; format=:latex))
    println(io, "\\]")
    println(io)
end

function _write_inventory(path::AbstractString, families;
    heading::Union{Nothing,AbstractString}=nothing,
    instance_label::AbstractString="registered")
    open(path, "w") do io
        println(io, "% Generated by scripts/analysis/generate_supplementary_equations.jl")
        heading === nothing || println(io, "\\subsubsection{$(_latex_escape(heading))}")
        for (key, equations) in sort!(collect(families); by=first)
            _write_family(io, key, equations; instance_label=instance_label)
        end
    end
    return path
end

function _changed_policy_families(baseline_signatures, policy_families)
    changed = Dict{Tuple{Symbol,Symbol},Vector{NamedTuple}}()
    for (key, equations) in policy_families
        baseline = get(baseline_signatures, key, Set{String}())
        affected = [
            equation for equation in equations
            if !(JCGEOutput.render_expr(_equation_expression(equation); format=:latex) in baseline)
        ]
        isempty(affected) && continue
        changed[key] = affected
    end
    return changed
end

function main()
    isdir(GENERATED_DIR) || error("Article generated directory does not exist: $(GENERATED_DIR)")
    baseline_context = _build_context(CERiseCGE.multi_region_model())
    baseline_families = _equation_families(baseline_context)
    baseline_signatures = _family_expression_signatures(baseline_families)
    _write_inventory(CORE_OUTPUT, baseline_families)

    open(POLICY_OUTPUT, "w") do io
        println(io, "% Generated by scripts/analysis/generate_supplementary_equations.jl")
        for (instrument, wedge, title) in POLICY_LISTING_SCENARIOS
            scenario = CERiseCGE.eu_wide_policy_scenario(instrument, wedge)
            context = _build_context(CERiseCGE.multi_region_model(; scenario=scenario))
            changed = _changed_policy_families(baseline_signatures,
                _equation_families(context))
            isempty(changed) && error("No policy-specific equation family was found for $(instrument).")
            println(io, "\\subsubsection{$(_latex_escape(title))}")
            for (key, equations) in sort!(collect(changed); by=first)
                _write_family(io, key, equations; instance_label="policy-affected")
            end
        end
    end

    println("Wrote $(CORE_OUTPUT) and $(POLICY_OUTPUT).")
end

main()
